name: Deploy to FTP server

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: site

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Install expect
        run: sudo apt install -y expect
      - name: Copy files to server
        run: expect -f <(bash ../scripts/generate-expect-script.sh ${{secrets.FTP_USERNAME}} ${{secrets.FTP_PASSWORD}})
