name: Deploy to FTP server

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: site

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Install expect
        run: sudo apt install -y expect
      - name: Copy files to server
        run: expect -c 'spawn ftp ftp://${{secrets.FTP_USERNAME}}:${{secrets.FTP_PASSWORD}}@ftpupload.net ; expect "ftp> " ; send "cd htdocs\r" ; expect "ftp> " ; send "put index.html\r" ; expect "ftp> " ; send "put main.js\r" ; expect "ftp> " ; send "put player.js\r" ; expect "ftp> " ; send "put styles/style.css\r" ; expect "ftp> " ; send "bye\r" '
